/**
 * Bypass technique engine for WAF/filter evasion
 * Uses LLM to generate intelligent bypasses based on blocked payloads
 * Implements systematic bypass attempt protocol
 */

export class BypassEngine {
  constructor(payloadGenerator, maxAttempts = 10) {
    this.payloadGenerator = payloadGenerator;
    this.attemptCount = 0;
    this.maxAttempts = maxAttempts;
    this.blockedPayloads = [];
    this.successfulBypass = null;
  }

  /**
   * Generate bypass variations for a blocked payload
   * Uses LLM to create intelligent bypasses based on why it was blocked
   * @param {string} blockedPayload - The payload that was blocked
   * @param {object} blockingContext - Information about why it was blocked
   * @param {object} vulnerability - Vulnerability context
   * @param {object} techContext - Technology context (DB, WAF, etc.)
   * @returns {Promise<Array>} Generated bypass payloads
   */
  async generateBypasses(blockedPayload, blockingContext, vulnerability, techContext) {
    this.blockedPayloads.push({
      payload: blockedPayload,
      context: blockingContext,
      timestamp: Date.now()
    });

    const bypassPrompt = this.buildBypassPrompt(
      blockedPayload,
      blockingContext,
      vulnerability,
      techContext
    );

    try {
      // Use payload generator's OpenAI client to generate bypasses
      const client = this.payloadGenerator.client;
      const response = await client.chat.completions.create({
        model: this.payloadGenerator.model,
        messages: [
          {
            role: 'system',
            content: `You are an expert at bypassing WAF and input filters. Generate bypass payloads that achieve the same goal as the blocked payload while evading detection.

Techniques you can use:
- Encoding (URL, double-encoding, Unicode, hex)
- Comment injection (/**/, --, #)
- Case variation (SeLeCt, sELEct)
- Whitespace substitution (tabs, newlines, /**/)
- String concatenation
- Alternative syntax
- Obfuscation

Return ONLY the bypass payloads, one per line, without explanations.`
          },
          {
            role: 'user',
            content: bypassPrompt
          }
        ],
        temperature: 0.8, // Higher temperature for creative bypasses
        max_tokens: 1500
      });

      const bypasses = this.parseBypassesFromResponse(
        response.choices[0].message.content
      );

      this.attemptCount += bypasses.length;
      return bypasses.slice(0, this.maxAttempts - this.attemptCount);
    } catch (error) {
      console.error('Failed to generate bypasses via LLM:', error.message);
      // Fallback to basic encoding bypasses
      return this.getFallbackBypasses(blockedPayload);
    }
  }

  /**
   * Build prompt for bypass generation
   * @private
   */
  buildBypassPrompt(blockedPayload, blockingContext, vulnerability, techContext) {
    let prompt = `The following payload was blocked:\n\n`;
    prompt += `**Blocked Payload:** ${blockedPayload}\n\n`;

    if (blockingContext.wafDetected) {
      prompt += `**WAF Detected:** ${blockingContext.wafName || 'Unknown'}\n`;
    }

    if (blockingContext.errorMessage) {
      prompt += `**Error/Block Message:** ${blockingContext.errorMessage}\n`;
    }

    if (blockingContext.httpStatus) {
      prompt += `**HTTP Status:** ${blockingContext.httpStatus}\n`;
    }

    prompt += `\n**Context:**\n`;
    if (techContext.database) {
      prompt += `- Database: ${techContext.database}\n`;
    }
    if (techContext.waf) {
      prompt += `- WAF: ${techContext.waf}\n`;
    }

    prompt += `\n**Goal:** ${vulnerability.goal || 'Execute the payload successfully'}\n\n`;

    if (this.blockedPayloads.length > 1) {
      prompt += `**Previously Blocked Payloads:**\n`;
      for (const blocked of this.blockedPayloads.slice(-3)) {
        prompt += `- ${blocked.payload}\n`;
      }
      prompt += `\n`;
    }

    prompt += `Generate 5-8 bypass variations that:\n`;
    prompt += `1. Achieve the same goal as the blocked payload\n`;
    prompt += `2. Use different encoding/obfuscation techniques\n`;
    prompt += `3. Avoid patterns that were already blocked\n`;
    prompt += `4. Are specific to ${techContext.database || 'the target database'}\n`;

    return prompt;
  }

  /**
   * Parse bypasses from LLM response
   * @private
   */
  parseBypassesFromResponse(response) {
    const bypasses = [];
    
    // Extract numbered list items
    const numberedPattern = /^\d+\.\s*(.+)$/gm;
    let match;
    while ((match = numberedPattern.exec(response)) !== null) {
      const payload = match[1].trim();
      const cleanPayload = payload.replace(/^`+|`+$/g, '').trim();
      if (cleanPayload) {
        bypasses.push(cleanPayload);
      }
    }

    // If no numbered list, try extracting from code blocks
    if (bypasses.length === 0) {
      const codeBlockPattern = /```[\w]*\n([\s\S]+?)\n```/g;
      while ((match = codeBlockPattern.exec(response)) !== null) {
        const lines = match[1].split('\n').filter(line => 
          line.trim() && !line.trim().startsWith('#')
        );
        bypasses.push(...lines.map(l => l.trim()));
      }
    }

    // Extract plain lines if nothing else worked
    if (bypasses.length === 0) {
      const lines = response.split('\n');
      for (const line of lines) {
        const trimmed = line.trim();
        if (trimmed && 
            !trimmed.startsWith('#') && 
            !trimmed.toLowerCase().includes('bypass') &&
            trimmed.length > 2) {
          bypasses.push(trimmed);
        }
      }
    }

    return bypasses;
  }

  /**
   * Get basic fallback bypasses if LLM fails
   * @private
   */
  getFallbackBypasses(blockedPayload) {
    const bypasses = [];
    
    // URL encoding
    bypasses.push(encodeURIComponent(blockedPayload));
    
    // Double URL encoding
    bypasses.push(encodeURIComponent(encodeURIComponent(blockedPayload)));
    
    // Case variation
    bypasses.push(blockedPayload.toUpperCase());
    bypasses.push(blockedPayload.toLowerCase());
    
    // Comment injection (for SQL)
    bypasses.push(blockedPayload.replace(/ /g, '/**/'));
    
    return bypasses.slice(0, 5);
  }

  /**
   * Check if bypass attempts exhausted
   */
  isExhausted() {
    return this.attemptCount >= this.maxAttempts;
  }

  /**
   * Get total attempts made
   */
  getTotalAttempts() {
    return this.attemptCount;
  }

  /**
   * Record successful bypass
   */
  recordSuccess(payload, technique) {
    this.successfulBypass = { payload, technique, timestamp: Date.now() };
  }

  /**
   * Get successful bypass if any
   */
  getSuccessfulBypass() {
    return this.successfulBypass;
  }
}

/**
 * Create bypass engine with LLM support
 */
export function createBypassEngine(payloadGenerator, maxAttempts = 10) {
  return new BypassEngine(payloadGenerator, maxAttempts);
}
